# generated by apply_part for the applied layout.
# Intentionally has no PART marker because it is target-specific, not a source copy.
from __future__ import annotations

import sys
from pathlib import Path

TARGET_ROOT = Path(__file__).resolve().parents[3]
COMPAT = TARGET_ROOT.joinpath('tests', 'compat')
SRC = TARGET_ROOT.joinpath('src')
if str(COMPAT) not in sys.path:
    sys.path.insert(0, str(COMPAT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
